# Generated by Django 5.0.3 on 2024-11-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdi_app', '0002_tranfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranfer',
            name='account_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tranfer',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
