# Generated by Django 5.0.3 on 2024-11-18 06:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdi_app', '0003_alter_tranfer_account_number_alter_tranfer_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='tranfer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
